<?php
/**
 * NDT4 Theme Functions
 *
 * @package NDT4
 * @since 4.0.0
 */

declare(strict_types=1);

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Theme version constant (pulled from style.css Version header)
 */
define( 'NDT4_VERSION', wp_get_theme()->get( 'Version' ) );

/**
 * Theme setup
 */
function ndt4_setup(): void {
	// Add theme support
	add_theme_support( 'title-tag' );
	add_theme_support( 'post-thumbnails' );
	add_theme_support( 'html5', [
		'search-form',
		'comment-form',
		'comment-list',
		'gallery',
		'caption',
		'style',
		'script',
	] );
	add_theme_support( 'customize-selective-refresh-widgets' );
	add_theme_support( 'wp-block-styles' );
	add_theme_support( 'responsive-embeds' );
	add_theme_support( 'editor-styles' );

	// Add editor stylesheet
	add_editor_style( 'assets/css/editor.css' );

	// Register navigation menus
	register_nav_menus( [
		'primary'   => __( 'Primary Menu', 'ndt4' ),
		'secondary' => __( 'Secondary Menu', 'ndt4' ),
	] );

	// Set content width
	$GLOBALS['content_width'] = 960;

	// Load text domain
	load_theme_textdomain( 'ndt4', get_template_directory() . '/languages' );
}
add_action( 'after_setup_theme', 'ndt4_setup' );

/**
 * Theme activation: Create default menu if none exists
 */
function ndt4_theme_activation(): void {
	// Check if primary menu location already has a menu assigned
	$locations = get_nav_menu_locations();
	if ( ! empty( $locations['primary'] ) ) {
		return;
	}

	// Check if any menus exist at all
	$menus = wp_get_nav_menus();
	if ( ! empty( $menus ) ) {
		// Menus exist but none assigned to primary - don't create a new one
		return;
	}

	// Create a new menu
	$menu_name = __( 'Primary Menu', 'ndt4' );
	$menu_id   = wp_create_nav_menu( $menu_name );

	if ( is_wp_error( $menu_id ) ) {
		return;
	}

	// Add Home menu item
	wp_update_nav_menu_item( $menu_id, 0, [
		'menu-item-title'   => __( 'Home', 'ndt4' ),
		'menu-item-url'	 => home_url( '/' ),
		'menu-item-status'  => 'publish',
		'menu-item-type'	=> 'custom',
	] );

	// Assign menu to primary location
	$locations['primary'] = $menu_id;
	set_theme_mod( 'nav_menu_locations', $locations );
}
add_action( 'after_switch_theme', 'ndt4_theme_activation' );

/**
 * Setup default widgets on theme activation
 *
 * Configures sidebar-nav with Recent Posts, Archives, and Categories widgets.
 * Only runs if the sidebar has no widgets configured.
 */
function ndt4_setup_default_widgets(): void {
	$sidebars_widgets = get_option( 'sidebars_widgets', [] );

	// Check if sidebar-nav already has widgets configured
	if ( ! empty( $sidebars_widgets['sidebar-nav'] ) ) {
		return;
	}

	// Set up widget instances
	// Recent Posts widget
	$recent_posts = get_option( 'widget_recent-posts', [] );
	$recent_posts[2] = [
		'title'  => '',
		'number' => 5,
	];
	update_option( 'widget_recent-posts', $recent_posts );

	// Archives widget
	$archives = get_option( 'widget_archives', [] );
	$archives[2] = [
		'title'    => '',
		'count'    => 0,
		'dropdown' => 0,
	];
	update_option( 'widget_archives', $archives );

	// Categories widget
	$categories = get_option( 'widget_categories', [] );
	$categories[2] = [
		'title'        => '',
		'count'        => 0,
		'hierarchical' => 0,
		'dropdown'     => 0,
	];
	update_option( 'widget_categories', $categories );

	// Assign widgets to sidebar
	$sidebars_widgets['sidebar-nav'] = [
		'recent-posts-2',
		'archives-2',
		'categories-2',
	];
	update_option( 'sidebars_widgets', $sidebars_widgets );
}
add_action( 'after_switch_theme', 'ndt4_setup_default_widgets' );

/**
 * Register widget areas
 */
function ndt4_widgets_init(): void {
	register_sidebar( [
		'name'          => __( 'Nav Sidebar', 'ndt4' ),
		'id'            => 'sidebar-nav',
		'description'   => __( 'Add widgets here to appear in your navigation sidebar.', 'ndt4' ),
		'before_widget' => '<section id="%1$s" class="widget %2$s">',
		'after_widget'  => '</section>',
	] );

}
add_action( 'widgets_init', 'ndt4_widgets_init' );

/**
 * Remove WordPress default block styles - Conductor handles all styling
 */
// function ndt4_dequeue_block_styles(): void {
// 	wp_dequeue_style( 'wp-block-library' );
// 	wp_dequeue_style( 'wp-block-library-theme' );
// 	wp_dequeue_style( 'wc-blocks-style' ); // WooCommerce if present
// }
// add_action( 'wp_enqueue_scripts', 'ndt4_dequeue_block_styles', 100 );

/**
 * Remove global styles (inline CSS generated by WordPress core)
 */
function ndt4_remove_global_styles(): void {
	remove_action( 'wp_enqueue_scripts', 'wp_enqueue_global_styles' );
	remove_action( 'wp_body_open', 'wp_global_styles_render_svg_filters' );
}
add_action( 'init', 'ndt4_remove_global_styles' );

/**
 * Disable block editor inline styles on frontend
 */
add_filter( 'should_load_separate_core_block_assets', '__return_false' );

/**
 * Enqueue scripts and styles
 */
function ndt4_scripts(): void {
	// External Conductor framework CSS
	wp_enqueue_style(
		'ndt-framework',
		'https://conductor.nd.edu/stylesheets/themes/ndt/4.0/ndt.css',
		[],
		null
	);

	// Theme styles
	wp_enqueue_style(
		'ndt4-theme',
		get_template_directory_uri() . '/assets/css/theme.css',
		[ 'ndt-framework' ],
		NDT4_VERSION
	);

	// Conditional animation CSS
	if ( get_theme_mod( 'ndt4_animate', false ) ) {
		wp_enqueue_style(
			'ndt4-animate',
			get_template_directory_uri() . '/assets/css/animate.css',
			[ 'ndt4-theme' ],
			NDT4_VERSION
		);
	}

	// External Conductor framework JS
	wp_enqueue_script(
		'ndt-framework',
		'https://conductor.nd.edu/javascripts/themes/ndt/4.0/ndt.js',
		[],
		null,
		true
	);

	// Theme JS
	wp_enqueue_script(
		'ndt4-theme',
		get_template_directory_uri() . '/assets/js/theme.js',
		[ 'ndt-framework' ],
		NDT4_VERSION,
		true
	);

	// Navigation JS
	wp_enqueue_script(
		'ndt4-navigation',
		get_template_directory_uri() . '/assets/js/navigation.js',
		[],
		NDT4_VERSION,
		true
	);

	// Localize script with theme data
	wp_localize_script( 'ndt4-theme', 'ndt4Data', [
		'ajaxUrl'   => admin_url( 'admin-ajax.php' ),
		'nonce'	 => wp_create_nonce( 'ndt4-nonce' ),
		'navStyle'  => ndt4_get_navigation_style(),
	] );

	// Comment reply script
	if ( is_singular() && comments_open() && get_option( 'thread_comments' ) ) {
		wp_enqueue_script( 'comment-reply' );
	}
}
add_action( 'wp_enqueue_scripts', 'ndt4_scripts' );

/**
 * Register custom post meta fields
 */
function ndt4_register_post_meta(): void {
	register_post_meta( 'page', 'ndt4_page_lede', [
		'show_in_rest'  => true,
		'single'        => true,
		'type'          => 'string',
		'auth_callback' => function() {
			return current_user_can( 'edit_posts' );
		},
	] );

}
add_action( 'init', 'ndt4_register_post_meta' );

/**
 * Enqueue block editor assets
 */
function ndt4_block_editor_assets(): void {
	wp_enqueue_style(
		'ndt4-editor',
		get_template_directory_uri() . '/assets/css/editor.css',
		[],
		NDT4_VERSION
	);

	$asset_file = get_template_directory() . '/assets/js/editor-sidebar.asset.php';
	$deps       = file_exists( $asset_file ) ? require $asset_file : [ 'dependencies' => [], 'version' => NDT4_VERSION ];

	wp_enqueue_script(
		'ndt4-editor-sidebar',
		get_template_directory_uri() . '/assets/js/editor-sidebar.js',
		array_merge(
			[ 'wp-plugins', 'wp-edit-post', 'wp-element', 'wp-components', 'wp-data', 'wp-core-data', 'wp-i18n' ],
			$deps['dependencies'] ?? []
		),
		$deps['version'] ?? NDT4_VERSION,
		true
	);
}
add_action( 'enqueue_block_editor_assets', 'ndt4_block_editor_assets' );

/**
 * Get navigation style setting
 *
 * @return string 'side' or 'top'
 */
function ndt4_get_navigation_style(): string {
	return get_theme_mod( 'ndt4_nav_style', 'side' );
}

/**
 * Check if current page should display full-width
 *
 * @return bool
 */
function ndt4_is_full_width(): bool {
	// Check page template
	if ( is_page_template( 'templates/template-full-width.php' ) ) {
		return true;
	}


	return false;
}

/**
 * Get latest news posts
 *
 * @param int $count Number of posts to retrieve.
 * @return WP_Query
 */
function ndt4_get_latest_news( int $count = 3 ): WP_Query {
	return new WP_Query( [
		'post_type'	  => 'ndt4_news',
		'posts_per_page' => $count,
		'orderby'		=> 'date',
		'order'		  => 'DESC',
	] );
}

/**
 * Add body classes
 *
 * Note: nav-top--true/nav-top--false classes are added directly in header.php
 * to match the Liquid template format.
 *
 * @param array $classes Existing body classes.
 * @return array Modified body classes.
 */
function ndt4_body_classes( array $classes ): array {
	// Remove classes that conflict with Conductor styles
	$classes = array_diff( $classes, [ 'search-results' ] );

	// Add full-width class
	if ( ndt4_is_full_width() ) {
		$classes[] = 'full-width';
	}

	// Add page--full-width when using full-width template
	if ( is_page_template( 'templates/template-full-width.php' ) ) {
		$classes[] = 'page--full-width';
	} elseif ( is_page() ) {
		// Add page--full-width when page has no sidebar
		$nav_style    = ndt4_get_navigation_style();
		$topnav       = ( 'top' === $nav_style );
		$is_top_level = ! wp_get_post_parent_id( get_the_ID() );
		$has_children = ndt4_page_has_children( get_the_ID() );
		$has_subnav   = ! $is_top_level || $has_children;
		$has_sidebar  = ! $topnav || $has_subnav;

		if ( ! $has_sidebar ) {
			$classes[] = 'page--full-width';
		}
	}

	// Add page--full-width for search results
	if ( is_search() ) {
		$classes[] = 'page--full-width';
	}

	// Add hfeed class for non-singular pages
	if ( ! is_singular() ) {
		$classes[] = 'hfeed';
	}

	return $classes;
}
add_filter( 'body_class', 'ndt4_body_classes' );

/**
 * Add custom classes to post_class()
 *
 * @param array $classes Existing post classes.
 * @return array Modified post classes.
 */
function ndt4_post_classes( array $classes ): array {
	$classes[] = 'card-container';
	$classes[] = 'article';
	return $classes;
}
add_filter( 'post_class', 'ndt4_post_classes' );

/**
 * Include required files
 */
require get_template_directory() . '/inc/customizer.php';
require get_template_directory() . '/inc/template-tags.php';
require get_template_directory() . '/inc/template-functions.php';
require get_template_directory() . '/inc/post-types/news.php';
require get_template_directory() . '/inc/taxonomies/news-category.php';
require get_template_directory() . '/inc/update-checker.php';

/**
 * Register custom block category
 *
 * @param array                   $categories Existing block categories.
 * @param WP_Block_Editor_Context $context    Block editor context.
 * @return array Modified block categories.
 */
function ndt4_block_categories( array $categories, WP_Block_Editor_Context $context ): array {
	array_unshift( $categories, [
		'slug'  => 'ndt4',
		'title' => __( 'NDT4', 'ndt4' ),
	] );

	return $categories;
}
add_filter( 'block_categories_all', 'ndt4_block_categories', 10, 2 );

/**
 * Register custom blocks from the blocks directory
 *
 * Each block should have its own subdirectory under /blocks/ with a block.json file.
 */
function ndt4_register_blocks(): void {
	$blocks_dir = get_template_directory() . '/blocks';

	if ( ! is_dir( $blocks_dir ) ) {
		return;
	}

	$block_dirs = glob( $blocks_dir . '/*/block.json' );

	foreach ( $block_dirs as $block_json ) {
		register_block_type( dirname( $block_json ) );
	}
}
add_action( 'init', 'ndt4_register_blocks' );

/**
 * Register block pattern categories
 *
 * Note: Patterns in /patterns/ directory are automatically registered by WordPress 6.0+
 * using file headers (Title, Slug, Categories, Description).
 */
function ndt4_register_block_pattern_categories(): void {
	register_block_pattern_category( 'ndt4-heroes', [
		'label' => __( 'NDT4 Heroes', 'ndt4' ),
	] );

	register_block_pattern_category( 'ndt4-content', [
		'label' => __( 'NDT4 Content', 'ndt4' ),
	] );

	register_block_pattern_category( 'ndt4-cta', [
		'label' => __( 'NDT4 Call to Action', 'ndt4' ),
	] );

	register_block_pattern_category( 'ndt4-news', [
		'label' => __( 'NDT4 News', 'ndt4' ),
	] );
}
add_action( 'init', 'ndt4_register_block_pattern_categories' );
